Aiming to fix a TensorFlow 'InternalError' from tensor_scatter_add. Lots of restructuring in order to sanitise sonnet modules
The objective here was to correct this error:

tensorflow.python.framework.errors_impl.InternalError: Missing 0-th output from {{node
KGMessagePassingLearner_1/kg_encoder/edge_model/edge_typewise_encoder/TensorScatterAdd}}

Caused by:
encoded_features = tf.tensor_scatter_add(encoded_features, indices_to_encode, encoded_feats)

Replicated by the test TestKGCN.test_kgcn_runs

I was unable to deduce the cause, and so have introduced an alternative implementation